"""ASCDC system constants and tuning parameters."""

# Counterfactual Evaluation Thresholds
COUNTERFACTUAL_NECESSITY_IMPACT_THRESHOLD = 0.75
COUNTERFACTUAL_NECESSITY_RATIO_THRESHOLD = 0.12
COUNTERFACTUAL_MEANINGFUL_IMPACT_THRESHOLD = 0.4
COUNTERFACTUAL_MEANINGFUL_RATIO_THRESHOLD = 0.06

# Instability Dynamics
INSTABILITY_GROWTH_RATE = 0.45
INSTABILITY_PRESSURE_TRIGGER = 1.25
INSTABILITY_DECAY_RATE = 0.82
INSTABILITY_RESET_DELTA = 0.15
INSTABILITY_RESET_MULTIPLIER = 0.35
INSTABILITY_ESCALATION_CAP = 3.0
INSTABILITY_ESCALATION_FACTOR = 0.4

# Pressure Calculation
PRESSURE_RETRY_WEIGHT = 0.75
PRESSURE_ERROR_WEIGHT = 0.75
PRESSURE_RETRY_BASE_WEIGHT = 0.35
PRESSURE_UTILIZATION_WEIGHT = 0.65
PRESSURE_MAX_RETRY = 2.0
PRESSURE_MAX_ERROR = 2.0

# Reward Function
REWARD_BASE_BONUS = 3.6
REWARD_LATENCY_PENALTY = 0.8
REWARD_QUEUE_PRESSURE_PENALTY = 1.1
REWARD_RETRY_PENALTY = 0.85
REWARD_ERROR_PENALTY = 0.85
REWARD_INSTABILITY_PENALTY = 0.1
REWARD_DRIFT_PENALTY = 0.12
REWARD_STABILITY_BONUS = 0.3
REWARD_PRESSURE_IMPROVEMENT_BONUS = 0.5
REWARD_PRESSURE_IMPROVEMENT_LARGE_BONUS = 1.0
REWARD_RESTART_PENALTY = 0.06
REWARD_SCALE_PENALTY = 0.02
REWARD_THROTTLE_PENALTY = 0.015
REWARD_TIMING_BONUS = 0.8
REWARD_PREMATURE_PENALTY = 0.35
REWARD_LATE_PENALTY = 0.2
REWARD_NOOP_STREAK_BONUS = 0.03
REWARD_NOOP_STREAK_CAP = 4
REWARD_NOOP_UNSTABLE_PENALTY = 0.08
REWARD_INACTION_PENALTY = 0.03

# Grading System Weights
GRADING_STABILITY_WEIGHT = 0.4
GRADING_TIMING_WEIGHT = 0.4
GRADING_SMOOTHNESS_WEIGHT = 0.2
GRADING_COLLAPSE_THRESHOLD = 5.0
GRADING_COLLAPSE_PENALTY = 0.2
GRADING_LATENCY_SCORE_DIVISOR = 10.0
GRADING_PRESSURE_SCORE_DIVISOR = 3.0
GRADING_LATENCY_WEIGHT = 0.35
GRADING_PRESSURE_WEIGHT = 0.25
GRADING_TRANSITION_STABILITY_WEIGHT = 0.4
GRADING_TIMING_TIMELY_WEIGHT = 0.45
GRADING_TIMING_MISSED_PENALTY = 0.35
GRADING_TIMING_UNNECESSARY_PENALTY = 0.25
GRADING_PRESSURE_FLIP_WEIGHT = 0.75
GRADING_ACTION_FLIP_WEIGHT = 0.25

# SmartAgent Planning
SMART_AGENT_HORIZON = 12
SMART_AGENT_DISCOUNT_FACTOR = 0.85
SMART_AGENT_ACTION_SWITCH_PENALTY = 0.15
SMART_AGENT_CONSERVATIVE_THRESHOLD = 0.4
SMART_AGENT_CRISIS_PRESSURE_THRESHOLD = 2.0
SMART_AGENT_CRISIS_BONUS = 0.8
SMART_AGENT_PREMATURE_PRESSURE_THRESHOLD = 0.8
SMART_AGENT_PREMATURE_PENALTY = 0.3
SMART_AGENT_COOLDOWN = 2
SMART_AGENT_DRIFT_THRESHOLD = 0.15
SMART_AGENT_STABLE_PRESSURE_THRESHOLD = 0.4
SMART_AGENT_STABLE_DRIFT_THRESHOLD = 0.03
SMART_AGENT_QUEUE_THRESHOLD = 0.1

# LearningAgent Q-Learning
LEARNING_AGENT_ALPHA = 0.4
LEARNING_AGENT_GAMMA = 0.95
LEARNING_AGENT_EPSILON = 0.1
LEARNING_AGENT_EPSILON_DECAY = 0.993
LEARNING_AGENT_MIN_EPSILON = 0.01
LEARNING_AGENT_ALPHA_DECAY = 0.998
LEARNING_AGENT_MIN_ALPHA = 0.01
LEARNING_AGENT_PRESSURE_GRANULARITY = 0.5
LEARNING_AGENT_CRISIS_EXPLORATION_MULTIPLIER = 0.5
LEARNING_AGENT_CALM_EXPLORATION_MULTIPLIER = 1.2
LEARNING_AGENT_CRISIS_THRESHOLD = 2.0
LEARNING_AGENT_CALM_THRESHOLD = 0.5
LEARNING_AGENT_ADAPTIVE_ALPHA_FACTOR = 0.2
LEARNING_AGENT_ADAPTIVE_ALPHA_CAP = 2.0
LEARNING_AGENT_MAX_STATES = 10000

# Drift Accumulation
DRIFT_ACCUMULATION_RATE = 0.02
DRIFT_ACCUMULATION_THRESHOLD = 0.6
DRIFT_DECAY_RATE = 0.85
DRIFT_SMOOTHING_WEIGHT = 0.8

# Latency Dynamics
LATENCY_PRESSURE_MULTIPLIER = 1.0

# Retry/Error Escalation
RETRY_ESCALATION_BASE = 0.12
RETRY_ESCALATION_INSTABILITY_WEIGHT = 0.08
ERROR_ESCALATION_BASE = 0.18
ERROR_ESCALATION_INSTABILITY_WEIGHT = 0.1
